# Generated by Django 5.2.7 on 2025-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
